server {
    listen 80;

    location /boss/ {
        alias /usr/share/nginx/html/boss/;
        index index.html;
        try_files $uri $uri/ /boss/index.html;
    }

    # Redirect root to /boss/
    location = / {
        return 301 /boss/;
    }
}
